version: '3.8'

services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: home_budget_db
      POSTGRES_USER: username
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: